#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export TERM="xterm-256color"

# Homebrew
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"

# Anaconda
export PATH="$HOME/anaconda2/bin:$PATH"


# Customize to your needs..
alias p='popd'
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less"
alias fd='find . -type d -name'
alias ff='find . -type f -name'

alias h='history'

alias rm='rm -i'
alias cp='rsync -ah --progress'
alias mv='mv -i'

#apt
alias apts='apt-cache search'
alias aptsow='apt-cache show'
alias apti='sudo apt-get install -V'
alias aptu='sudo apt-get update'
alias aptrm='sudo apt-get remove'
alias aptpurge='sudo apt-get remove --purge'
