#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source local config
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/zlocal.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/zlocal.zsh"
fi

# ZSH options
unsetopt correct
export TERM="xterm-256color"

# PATH
export PATH="$HOME/bin:$PATH"

# Homebrew
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"

# Anaconda
export PATH="$HOME/anaconda2/bin:$PATH"

# Go
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$HOME/go/bin

# NIX
if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then . $HOME/.nix-profile/etc/profile.d/nix.sh; fi 


# Customize to your needs..
alias p='popd'
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less"
alias fd='find . -type d -name'
alias ff='find . -type f -name'

alias h='history'

unalias rm cp mv
alias rm='rm -I'
alias cp='rsync -ah --progress'
alias mv='mv -i'
alias wget='wget -c'

#apt
alias apts='apt-cache search'
alias aptshow='apt-cache show'
alias apti='sudo apt-get install -V'
alias aptu='sudo apt-get update'
alias aptrm='sudo apt-get remove'
alias aptpurge='sudo apt-get remove --purge'
